import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";
import Navbar from "@/components/Navbar";
import GlobalGridLayout from "@/components/GlobalGridLayout";

const publicSans = Public_Sans({
    variable: "--font-public-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Fintacker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${publicSans.variable} antialiased`}>
                <main>
                    <Navbar />
                    <GlobalGridLayout>
                        <SideNavbar />
                        {children}
                    </GlobalGridLayout>
                </main>
            </body>
        </html>
    );
}
